### PR TITLE
added support for caja file manager

### PR DESCRIPTION
**Pull request by mattmart3**
I just did some renaming as you did for the nemo branch and tested it. It works as expected.
You may want to create the 'caja' branch first and then I can edit the pull request to let you merge it on your 'caja' branch.

### CODE REVIEW

**Comment by Diaoul** [comment]
Please update the docs so branches redirect to each other (requires a PR in the other branches too).

**Comment by mattmart3** [comment]
I am sorry, do you mean should I add links to each branch in every readme?
So that master readme should point to Nemo and caja branches, Nemo readme should point to master and caja branches and caja readme should point to master and Nemo branches?
Or are you referring about some docs other than readme file?

**Comment by Diaoul** [comment]
Sorry for the confusion. Yes I meant the readme. Docs is a big word for a
readme I have to admit :)

Le 4 janv. 2018 1:38 PM, "Matteo Martelli" <notifications@github.com> a
écrit :

I am sorry, do you mean should I add links to each branch in every readme?
So that master readme should point to Nemo and caja branches, Nemo readme
should point to master and caja branches and caja readme should point to
master and Nemo branches?
Or are you referring about some docs other than readme file?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Diaoul/nautilus-subliminal/pull/14#issuecomment-355272203>,
or mute the thread

**Comment by mattmart3** [comment]
Don't worry, that is fine. I just wanted to be sure not to misunderstand something :)
I created two pull requests for docs update and one pull request for the caja branch so I am closing this one.
Hope I did everything right.

**Pull request closed without merging**
